---
# Wait 8 minutes for us to be in the Finishing state before we
# decide the washing machine has finished. This way, if the
# washing machine is in between cycles and the power drops, we
# won't mark the washing machine cycle as finished too early.

alias: Set washing machine clean after timeout
trigger:
  - platform: state
    entity_id: sensor.washer_state
    to: Finishing
    for:
      minutes: 5
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.washer_state
      state: Finishing
action:
  - service: mqtt.publish
    data:
      topic: hass/state/washer
      payload: "Clean"
      retain: "true"
