---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named integrations
  customize: !include customize.yaml

discovery:

map:

frontend:
  themes: !include themes.yaml
  javascript_version: latest

lutron_caseta:
  host: 192.168.1.19
  keyfile: /home/homeassistant/.homeassistant/ssl/lutron/caseta.key
  certfile: /home/homeassistant/.homeassistant/ssl/lutron/caseta.crt
  ca_certs: /home/homeassistant/.homeassistant/ssl/lutron/caseta-bridge.crt

august:
  login_method: phone
  username: !secret august_username
  password: !secret august_password

badnest:
  issue_token: !secret badnest_issue_token
  cookie: !secret badnest_cookie
  region: ca

climate:
  - platform: badnest
    scan_interval: 10

life360:
  accounts:
    username: !secret life360_username
    password: !secret life360_password
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  # MPH, assuming imperial units.
  # If using metric (KPH), equivalent would be 29
  driving_speed: 18
  # Set comm error thresholds so first is not logged,
  # second is logged as a WARNING, and third and fourth
  # are logged as ERRORs.
  warning_threshold: 2
  error_threshold: 3

google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_client_secret

mqtt:
  broker: 192.168.1.115
  username: !secret mqtt_username
  password: !secret mqtt_password

utility_meter:
  printer_daily:
    source: sensor.plug_1_energy_today
    cycle: daily
    tariffs:
      - onpeak
      - midpeak
      - offpeak
  printer_weekly:
    source: sensor.plug_1_energy_today
    cycle: weekly
    tariffs:
      - onpeak
      - midpeak
      - offpeak
  printer_monthly:
    source: sensor.plug_1_energy_today
    cycle: monthly
    tariffs:
      - onpeak
      - midpeak
      - offpeak
  washer_daily:
    source: sensor.washer_energy_today
    cycle: daily
    tariffs:
      - onpeak
      - midpeak
      - offpeak
  washer_weekly:
    source: sensor.washer_energy_today
    cycle: weekly
    tariffs:
      - onpeak
      - midpeak
      - offpeak
  washer_monthly:
    source: sensor.washer_energy_today
    cycle: monthly
    tariffs:
      - onpeak
      - midpeak
      - offpeak

binary_sensor:
  - platform: workday
    country: CA
    province: "ON"
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

octoprint:
  - host: 192.168.1.6
    api_key: !secret octoprint_api_key
    bed: true
    number_of_tools: 2
    sensors:
      monitored_conditions:
        - 'Current State'
        - 'Temperatures'
        - 'Job Percentage'
        - 'Time Elapsed'
        - 'Time Remaining'

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.1.115:8090/still.jpg
    mjpeg_url: http://192.168.1.115:8090/live.mjpg

################
# Notifications
################

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret sarah_chat

################
# Logging
################
logger:
  default: warning

logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.date_iso
      - sensor.time_date
    domains:
      - sun

system_health:

fastdotcom:
  scan_interval:
    minutes: 120

pi_hole:
  host: 192.168.1.115
  api_key: !secret pi_hole_api_key

################
# Files to include
################
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
sensor: !include sensors.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
notify: !include notify.yaml
