
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

map:

system_health:

frontend:
  themes: !include themes.yaml
  javascript_version: latest


august:
  login_method: phone
  username: !secret august_username
  password: !secret august_password

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300


logger:
  default: warning

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


