
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

discovery:
  ignore:
    - igd
    - homekit

map:

zone:
  - name: home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 200 #In meters

proximity:
  home:
    devices:
      - device_tracker.life360_sarah_boyd
      - device_tracker.life360_scott_young
    tolerance: 100 #In meters
    unit_of_measurement: km #Used for travel distances

lovelace:
  mode: yaml

frontend:
  themes: !include themes.yaml
  javascript_version: latest


weather:
  - platform: darksky
    api_key: !secret darksky_api

lutron_caseta:
  host: 192.168.1.19
  keyfile: ssl/lutron/caseta.key
  certfile: ssl/lutron/caseta.crt
  ca_certs: ssl/lutron/caseta-bridge.crt

august:
  login_method: phone
  username: !secret august_username
  password: !secret august_password

badnest:
  issue_token: !secret badnest_issue_token
  cookie: !secret badnest_cookie
  region: ca

climate:
  - platform: badnest
    scan_interval: 10

sensor:
  - platform: badnest

life360:
  accounts:
    username: !secret life360_username
    password: !secret life360_password
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  # MPH, assuming imperial units.
  # If using metric (KPH), equivalent would be 29
  driving_speed: 18
  # Set comm error thresholds so first is not logged,
  # second is logged as a WARNING, and third and fourth
  # are logged as ERRORs.
  warning_threshold: 2
  error_threshold: 3

# google:
#   client_id: !secret google_cal_client_id
#   client_secret: !secret google_cal_client_secret

mqtt:
  broker: 192.168.1.115

utility_meter:
  printer_daily:
    source:  sensor.plug_1_energy_today
    cycle: daily
    tariffs:
      - onpeak
      - midpeak
      - offpeak
  printer_weekly:
    source:  sensor.plug_1_energy_today
    cycle: weekly
    tariffs:
      - onpeak
      - midpeak
      - offpeak
  printer_monthly:
    source:  sensor.plug_1_energy_today
    cycle: monthly
    tariffs:
      - onpeak
      - midpeak
      - offpeak

binary_sensor:
  - platform: workday
    country: CA
    province: "ON"


################
# Notifications
################

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret sarah_chat

################
# Media
################

# media_player:
#   - platform: vizio
#     host: 192.168.1.9
#     access_token: !secret vizio_token    

################
# Logging
################
logger:
  default: warning

logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.date_iso
      - sensor.time_date
    domains:
      - sun
#recorder: 
  #db_url: !secret db_url
 # purge_keep_days: 7
  # exclude: 
  #   domains:
  #     - media_player
  #     - weather
  #     - input_select
  #     - input_number


#history:

system_health:

fastdotcom:
  scan_interval:
      minutes: 120

################
# Files to include
################
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
sensor: !include sensors.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
notify: !include notify.yaml
