---
alias: Mark person as away
trigger:
  - platform: state
    entity_id: input_select.sarah_status_dropdown
    to: Just Left
    for:
      minutes: 10
  - platform: state
    entity_id: input_select.scott_status_dropdown
    to: Just Left
    for:
      minutes: 10
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'input_select.sarah_status_dropdown' %}
            input_select.sarah_status_dropdown
        {% else %}
            input_select.scott_status_dropdown
        {% endif %}
      option: Away
