---
alias: Mark person as extended away
trigger:
  - platform: state
    entity_id: input_select.sarah_status_dropdown
    to: Away
    for:
      hours: 24
  - platform: state
    entity_id: input_select.scott_status_dropdown
    to: Away
    for:
      hours: 24
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'input_select.sarah_status_dropdown' %}
            input_select.sarah_status_dropdown
        {% else %}
            input_select.scott_status_dropdown
        {% endif %}
      option: Extended Away
