---
alias: Turn on bedroom lights before bed
trigger:
  - entity_id: media_player.living_room_chromecast
    platform: state
    from: "on"
    to: "off"
    for: 00:01:00
condition:
  - condition: state
    entity_id: media_player.living_room_chromecast
    state: "off"
  - condition: time
    after: "21:00:00"
    before: "02:00:00"
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.sarah_status
        state: Home
      - condition: state
        entity_id: sensor.scott_status
        state: Home
action:
  service: homeassistant.turn_on
  entity_id: light.bedroom
