---
alias: Wake Up Light Bedroom
trigger:
  platform: template
  value_template: "{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state }}"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: "on"
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekends
          state: "on"
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
action:
  service: script.wakeup_bedroom
