---
id: "telegramremoveinline"
alias: "Telegram callback to remove keyboard"
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: "/removekeyboard"
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: "{{ trigger.event.data.id }}"
      message: "OK"
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: "{{ trigger.event.data.message.message_id }}"
      chat_id: "{{ trigger.event.data.user_id }}"
      inline_keyboard: []
