---
id: "telegramrepeat30m"
alias: "Telegram callback to repeat message in 30 minutes"
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: "/30m"
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: "{{ trigger.event.data.id }}"
      message: "OK, reminding you in 30 minutes"
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: "{{ trigger.event.data.message.message_id }}"
      chat_id: "{{ trigger.event.data.user_id }}"
      inline_keyboard: []
  - delay: "00:30:00"
  - service: notify.telegram_sarah
    data_template:
      message: "{{ trigger.event.data.message.text }}"
      data:
        inline_keyboard:
          - "30 Minutes:/30m, 1 Hour:/1h, already empty:/empty_washer"
          - "No reminder:/removekeyboard"
