---
alias: Send alert to google home if we should start the cars before work
trigger:
  platform: time
  at: "06:40:00"
condition:
  - condition: template
    value_template: "{{ states.sensor.dark_sky_temperature.state | float < 2 }}"
  - condition: or
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: calendar.off_work
        state: "on"
action:
  - service: tts.google_say
    entity_id: media_player.living_room_speaker
    data_template:
      message: "The temperature outside is currently {{ states.sensor.dark_sky_temperature.state }} degrees, consider starting the cars"
      cache: false
