---
alias: Turn Radio on when everyone is away
trigger:
  platform: state
  entity_id: group.family
  to: "not_home"
condition: []
action:
  - service: media_player.volume_set
    entity_id: media_player.living_room_speaker
    data:
      volume_level: 0.20
  - service: media_player.play_media
    entity_id: media_player.living_room_speaker
    data:
      media_content_id: "http://corus.leanstream.co/CKDKFM-MP3?tunein"
      media_content_type: "audio/mp4"
