---
alias: Set off peak hydro hours
trigger:
  - platform: time
    at: "19:00:00"
action:
  - service: utility_meter.select_tariff
    entity_id: utility_meter.printer_daily
    data:
      tariff: offpeak
  - service: utility_meter.select_tariff
    entity_id: utility_meter.printer_weekly
    data:
      tariff: offpeak
  - service: utility_meter.select_tariff
    entity_id: utility_meter.printer_monthly
    data:
      tariff: offpeak
  - service: utility_meter.select_tariff
    entity_id: utility_meter.washer_daily
    data:
      tariff: offpeak
  - service: utility_meter.select_tariff
    entity_id: utility_meter.washer_weekly
    data:
      tariff: offpeak
  - service: utility_meter.select_tariff
    entity_id: utility_meter.washer_monthly
    data:
      tariff: offpeak
