---
# Restart HA to keep it fresh
alias: Restart HA
initial_state: false
trigger:
  platform: time
  at: "02:00:00"
condition:
  condition: time
  weekday:
    - sun
    - wed
    - fri
action:
  - service: homeassistant.restart
