---
alias: Monitor front door brightness
trigger:
  - platform: state
    entity_id: sensor.front_hall_light_brightness
condition:
  - condition: state
    entity_id: light.front_foyer_main_lights
    state: "on"
  - condition: template
    value_template: >
      {{ trigger.from_state.state != 'None' }}
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.front_hall_light_brightness
      value: "{{ state_attr('light.front_foyer_main_lights', 'brightness') }}"
