- alias: Set off peak hydro hours
  trigger:
    - platform: time
      at: '19:00:00'
  action:
    - service: utility_meter.select_tariff
      entity_id: utility_meter.printer_daily
      data:
        tariff: offpeak
    - service: utility_meter.select_tariff
      entity_id: utility_meter.printer_weekly
      data:
        tariff: offpeak
    - service: utility_meter.select_tariff
      entity_id: utility_meter.printer_monthly
      data:
        tariff: offpeak
# - alias: Set mid peak hydro hours
#   trigger:
#     - platform: time
#       at: '11:00:00'
#   condition:
#     condition: state
#     entity_id: 'binary_sensor.workday_sensor'
#     state: 'on'
#   action:
#     - service: utility_meter.select_tariff
#       entity_id: utility_meter.printer_daily
#       tariff: midpeak
#     - service: utility_meter.select_tariff
#       entity_id: utility_meter.printer_weekly
#       tariff: midpeak
#     - service: utility_meter.select_tariff
#       entity_id: utility_meter.printer_monthly
#       tariff: midpeak
# - alias: Set on peak hydro hours
#   trigger:
#     - platform: time
#       at: '07:00:00'
#     - platform: time
#       at: '17:00:00'
#   condition:
#     condition: state
#     entity_id: 'binary_sensor.workday_sensor'
#     state: 'on'
#   action:
#     - service: utility_meter.select_tariff
#       entity_id: utility_meter.printer_daily
#       tariff: onpeak
#     - service: utility_meter.select_tariff
#       entity_id: utility_meter.printer_weekly
#       tariff: onpeak
#     - service: utility_meter.select_tariff
#       entity_id: utility_meter.printer_monthly
#       tariff: onpeak
- id: '1579319582233'
  alias: New Automation
  description: ''
  trigger:
  - at: '19:00:00'
    platform: time
  condition: []
  action:
  - data:
      tariff: offpeak
    entity_id: utility_meter.printer_daily
    service: utility_meter.select_tariff
  