- alias: 'Away Mode'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.family
    to: 'not_home'
  action:
  - service: climate.set_preset_mode
    data:
      entity_id: climate.kitchen_thermostat
      preset_mode: 'eco'
  - service: notify.telegram_sarah
    data:
      message: Nest set to Away Mode!
- alias: 'Climate Proximity'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: proximity.home
    below: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: template
        value_template: '{{ states.proximity.home.attributes.dir_of_travel == "towards" }}'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.kitchen_thermostat
        preset_mode: 'none'
    - service: climate.set_hvac_mode
      data_template:
        entity_id: climate.kitchen_thermostat
        hvac_mode: >
          {% if states('sensor.season') == 'spring' or states('sensor.season') == 'summer' %}
            cool
          {% elif states('sensor.season') == 'autumn' %}
            auto
          {% else %}
            heat
          {% endif %}
    - service: notify.telegram_sarah
      data:
        message: Nest - proximity detected, eco turned off