---

- alias: Mark person as just arrived
  trigger:
    - entity_id: device_tracker.life360_sarah_boyd
      platform: state
      from: not_home
      to: home
    - entity_id: device_tracker.life360_scott_young
      platform: state
      from: not_home
      to: home
  action:
    - data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.life360_sarah_boyd' %}
              input_select.sarah_status_dropdown
          {% else %}
              input_select.scott_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'device_tracker.life360_sarah_boyd' %}
              {% if states.input_select.sarah_status_dropdown.state == 'Just Left' %}
                  Home
              {% else %}
                  Just Arrived
              {% endif %}
          {% else %}
              {% if states.input_select.scott_status_dropdown.state == 'Just Left' %}
                  Home
              {% else %}
                  Just Arrived
              {% endif %}
          {% endif %}
      service: input_select.select_option
- alias: Mark person as home
  trigger:
    - platform: state
      entity_id: input_select.sarah_status_dropdown
      to: Just Arrived
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.sarah_status_dropdown
      from: Just Left
      to: Just Arrived
    - platform: state
      entity_id: input_select.scott_status_dropdown
      to: Just Arrived
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.scott_status_dropdown
      from: Just Left
      to: Just Arrived
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.sarah_status_dropdown'%}
              input_select.sarah_status_dropdown
          {% else %}
              input_select.scott_status_dropdown
          {% endif %}
        option: Home
- alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: device_tracker.life360_sarah_boyd
      from: home
      to: not_home
    - platform: state
      entity_id: device_tracker.life360_scott_young
      from: home
      to: not_home
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.life360_sarah_boyd' %}
              input_select.sarah_status_dropdown
          {% else %}
              input_select.scott_status_dropdown
          {% endif %}
        option: Just Left
- alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.sarah_status_dropdown
      to: Just Left
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.scott_status_dropdown
      to: Just Left
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.sarah_status_dropdown' %}
              input_select.sarah_status_dropdown
          {% else %}
              input_select.scott_status_dropdown
          {% endif %}
        option: Away
- alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.sarah_status_dropdown
      to: Away
      for:
        hours: 24
    - platform: state
      entity_id: input_select.scott_status_dropdown
      to: Away
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.sarah_status_dropdown' %}
              input_select.sarah_status_dropdown
          {% else %}
              input_select.scott_status_dropdown
          {% endif %}
        option: Extended Away
- alias: Turn off automations when both people are Extended Away
  trigger:
    - platform: state
      entity_id: input_select.sarah_status_dropdown
      to: Extended Away
    - platform: state
      entity_id: input_select.scott_status_dropdown
      to: Extended Away
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.sarah_status_dropdown
        state: Extended Away
      - condition: state
        entity_id: input_select.scott_status_dropdown
        state: Extended Away
  action:
    - service: automation.turn_off
      entity_id: automation.wake_up_light_bedroom
    - service: automation.turn_off
      entity_id: automation.turn_on_bedroom_lights_before_bed
- alias: Turn on automations when at least one person returns
  trigger:
    - platform: state
      entity_id: input_select.sarah_status_dropdown
      from: Extended Away
      to: Just Arrived
    - platform: state
      entity_id: input_select.sarah_status_dropdown
      from: Extended Away
      to: Home
    - platform: state
      entity_id: input_select.scott_status_dropdown
      from: Extended Away
      to: Just Arrived
    - platform: state
      entity_id: input_select.scott_status_dropdown
      from: Extended Away
      to: Home
  action:
    - service: automation.turn_on
      entity_id: automation.wake_up_light_bedroom
    - service: automation.turn_on
      entity_id: automation.turn_on_bedroom_lights_before_bed
