# Set theme on HA start
- alias: Set theme and states at startup
  trigger:
    - platform: homeassistant
      event: start
  action:
    # - service: frontend.set_theme
    #   data:
    #     name: Dark - Blue
    - service: mqtt.publish
      data:
        topic: hass/state/dryer
        payload: 'Idle'
        retain: 'true'
    - service: mqtt.publish
      data:
        topic: hass/state/washer
        payload: 'Idle'
        retain: 'true'

# restart HA to keep it fresh
- alias: Restart HA
  trigger:
    platform: time
    at: "02:00:00"
  condition:
    condition: time
    weekday:
    - sun
    - wed
    - fri
  action:
    - service: homeassistant.restart
