- alias: Turn on Christmas Tree when we get home
  initial_state: 'off'
  trigger:
  - entity_id: sensor.sarah_status
    platform: state
    to: Just Arrived
    for:
      minutes: 5
  - entity_id: sensor.scott_status
    platform: state
    to: Just Arrived
    for:
      minutes: 5
  condition: []
  action: 
    - service: mqtt.publish
      data:
        topic: cmnd/sonoff-plug-1/POWER
        payload: 'ON'
- alias: Turn off Christmas Tree when we both leave
  initial_state: 'off'
  trigger:
  - entity_id: sensor.sarah_status
    platform: state
    to: Away
  - entity_id: sensor.scott_status
    platform: state
    to: Away
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.sarah_status
        state: Away
      - condition: state
        entity_id: sensor.scott_status
        state: Away
  action: 
    - service: mqtt.publish
      data:
        topic: cmnd/sonoff-plug-1/POWER
        payload: 'OFF'
