---
alias: Set Christmas Tree automations at startup
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.christmas_lights
    state: "on"
action:
  - service: automations.trigger
    entity_id: automation.turn_off_outside_lights
