---
alias: Turn off Christmas automations
trigger:
  - entity_id: input_boolean.christmas_automations
    platform: state
    to: "off"
condition: []
action:
  - service: automation.turn_off
    entity_id: automation.turn_off_tree
  - service: automation.turn_off
    entity_id: automation.turn_on_tree
