---
alias: Turn off Christmas Tree at night
initial_state: false
trigger:
  - entity_id: lights.main_floor_lights
    platform: state
    to: 'off'
condition:
  - condition: state
    entity_id: sensor.globe_plug_3_power
    state: "on"
  - condition: state
    entity_id: media_player.living_room_chromecast
    state: "off"
  - condition: time
    after: "21:00:00"
    before: "02:00:00"
action:
  - service: script.toggle_globe_plug
    data:
      plug: globeplug3
