---
alias: Turn on Christmas Tree when we get up
initial_state: false
trigger:
  - entity_id: light.living_room_main_lights
    platform: state
    to: 'on'
  - entity_id: light.dining_room_chandelier
    platform: state
    to: 'on'
  - entity_id: light.front_foyer_main_lights
    platform: state
    to: 'on'
  - entity_id: light.hue_color_lamp_1
    platform: state
    to: 'on'
    for:
      minutes: 20
condition:
  - condition: state
    entity_id: sensor.globe_plug_3_power
    state: "OFF"
  - condition: time
    after: '06:00:00'
    before: '11:00:00'
action:
  - service: script.toggle_globe_plug
    data:
      plug: globeplug3
