---
alias: Turn off Christmas Tree when we both leave
initial_state: false
trigger:
  - entity_id: sensor.sarah_status
    platform: state
    to: Away
  - entity_id: sensor.scott_status
    platform: state
    to: Away
condition:
  - condition: state
    entity_id: sensor.globe_plug_3_power
    state: "ON"
  - condition: state
    entity_id: sensor.sarah_status
    state: Away
  - condition: state
    entity_id: sensor.scott_status
    state: Away
action:
  - service: script.toggle_globe_plug
    data:
      plug: globeplug3
