---
alias: Turn on Christmas Tree when we get home
initial_state: false
trigger:
  - entity_id: sensor.sarah_status
    platform: state
    to: Just Arrived
    for:
      minutes: 5
  - entity_id: sensor.scott_status
    platform: state
    to: Just Arrived
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: sensor.globe_plug_3_power
    state: "off"
action:
  - service: script.toggle_globe_plug
    data:
      plug: globeplug3
