---
alias: Turn off Christmas Tree when we both leave
initial_state: false
trigger:
  - entity_id: sensor.sarah_status
    platform: state
    to: Away
  - entity_id: sensor.scott_status
    platform: state
    to: Away
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.sarah_status
      state: Away
    - condition: state
      entity_id: sensor.scott_status
      state: Away
action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoff-plug-1/POWER
      payload: "OFF"
