---
alias: Turn on Christmas automations
trigger:
  - entity_id: input_boolean.christmas_automations
    platform: state
    to: "on"
condition: []
action:
  - service: automation.turn_on
    entity_id: automation.turn_off_christmas_tree_when_we_both_leave
  - service: automation.turn_on
    entity_id: automation.turn_on_christmas_tree_when_we_get_home
