---
alias: Turn off Christmas Tree at night
initial_state: false
trigger:
  - entity_id: light.living_room_main_lights
    platform: state
    to: 'off'
condition:
  - condition: state
    entity_id: sensor.globe_plug_3_power
    state: "ON"
action:
  - service: script.toggle_globe_plug
    data:
      plug: globeplug3
