---

name: Home
weather: weather.dark_sky
rooms: !include_dir_list ./rooms
most_used:
  - entity_id: sensor.plug_1_power_state
    name: Fabricator
  - entity_id: light.living_room_main_lights
    name: Living Room
  - entity_id: switch.pi_hole
    name: Pi-hole
  - entity_id: lock.front_door
    name: Front Door
  - entity_id: sensor.washer_state
    name: Washer
  - entity_id: media_player.vizio_smartcast
    name: TV
  - entity_id: sensor.plug_2_power_state
    name: Ghost Cam
scenes:
  - entity_id: scene.everything_off
media:
  - name: Plex
    service: script.launch_plex
    image: "/local/images/plex.png"
  - name: Netflix
    service: script.launch_netflix
    image: "/local/images/netflix.png"
  - name: Prime
    service: script.launch_prime
    image: "/local/images/prime.png"
