---

name: Home
weather: weather.dark_sky
rooms: !include_dir_list ./rooms
most_used:
  - entity_id: sensor.plug_1_power_state
    name: Fabricator
  - entity_id: light.living_room_main_lights
    name: Living Room
  - entity_id: switch.pi_hole
    name: Pi-hole
  - entity_id: lock.front_door
    name: Front Door
  - entity_id: sensor.washer_state
    name: Washer
  - entity_id: media_player.living_room_chromecast
    name: TV
  - entity_id: sensor.globe_plug_1_power
    name: Wax Melt
  - entity_id: sensor.globe_plug_2_power
    name: Ghost Cam
scenes:
  - entity_id: scene.everything_off
media:
  - name: Plex
    service: script.launch_plex
    image: "/local/images/plex.png"
  - name: Netflix
    service: script.launch_netflix
    image: "/local/images/netflix.png"
  - name: Prime
    service: script.launch_prime
    image: "/local/images/prime.png"
media_server_system_stats:
  - name: CPU
    entity_id: sensor.glances_cpu_used
  - name: RAM
    entity_id: sensor.glances_ram_used_percent
  - name: Disk
    entity_id: sensor.media_drive_usage
media_server_service_checker:
  - name: Plex
    entity_id: sensor.plex_online
  - name: qBittorrent
    entity_id: sensor.qbittorrent_online
  - name: Tautulli
    entity_id: sensor.tautulli_online
  - name: Sonarr
    entity_id: sensor.sonarr_online
  - name: Radarr
    entity_id: sensor.radarr_online
  - name: Jackett
    entity_id: sensor.jackett_online
