---
name: Home Assistant CI

on:
  push:
  pull_request:

jobs:
  home_assistant_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: |
          cp .stubs/secrets.yaml homeassistant/secrets.yaml
          cp .stubs/google_token.json homeassistant/google_token.json
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config ./homeassistant/ --script check_config --info all
