---
alias: "Turn off wax melter after 3 hours"
trigger:
  platform: state
  entity_id: sensor.globe_plug_1_power
  to: "ON"
  for:
    hours: 3
action:
  - service: mqtt.publish
    data:
      topic: cmnd/globeplug1/Power
      payload: "Off"
